version: "3"
services:
  csa-db:
    image: postgres:14.0
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_DB: portfolio-db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - './redis_data:/bitnami/redis/data'
